#!/bin/bash

remote="$1"
url="$2"
branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$remote" == "origin" && "$branch" == "master" ]];
then
	commit-test 'Reviewer One <one@example.com>' 'Reviewer Two <two@example.com>' || exit
fi
